"""add triage verdict to poll runs

Revision ID: c973ea227c59
Revises: 54b25ef8521b
Create Date: 2026-08-24 14:42:53.829312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c973ea227c59"
down_revision: Union[str, Sequence[str], None] = "54b25ef8521b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "poll_runs", sa.Column("triage_category", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "poll_runs", sa.Column("triage_needs_human", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "poll_runs", sa.Column("triage_confidence", sa.Float(), nullable=True)
    )
    op.add_column("poll_runs", sa.Column("triage_summary", sa.Text(), nullable=True))
    op.add_column(
        "poll_runs", sa.Column("triage_source", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "poll_runs", sa.Column("triaged_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("poll_runs", "triaged_at")
    op.drop_column("poll_runs", "triage_source")
    op.drop_column("poll_runs", "triage_summary")
    op.drop_column("poll_runs", "triage_confidence")
    op.drop_column("poll_runs", "triage_needs_human")
    op.drop_column("poll_runs", "triage_category")
    # ### end Alembic commands ###
